# Build options
source:           /srv/jekyll/source
destination:      /srv/jekyll/_site

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dr. Mario
baseurl:          /

author:
  name:           'Mario López Martínez'

gems: 
                - jekyll-paginate
                - jekyll-gist

paginate:         5
paginate_path:    "page:num"

exclude:
                - docker-compose
                - .gitignore